### ISSUE TITLE
IOError from `make clean`

### ISSUE THREAD

**Issue by chadwhitacre** [AspenWeb/pando.py#190]
```
$ make clean
make is deprecated. Trying 'python build.py clean'...
Traceback (most recent call last):
  File "/Users/whit537/lib/python2.7/site.py", line 553, in <module>
    main()
  File "/Users/whit537/lib/python2.7/site.py", line 535, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/whit537/lib/python2.7/site.py", line 268, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/whit537/lib/python2.7/site.py", line 243, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/whit537/lib/python2.7/site.py", line 233, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/whit537/lib/python2.7/sysconfig.py", line 535, in get_config_var
    return get_config_vars().get(name)
  File "/Users/whit537/lib/python2.7/sysconfig.py", line 434, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/Users/whit537/lib/python2.7/sysconfig.py", line 287, in _init_posix
    raise IOError(msg)
IOError: invalid Python installation: unable to open /Users/whit537/lib/python2.7/config/Makefile (No such file or directory)
Traceback (most recent call last):
  File "/Users/whit537/lib/python2.7/site.py", line 553, in <module>
    main()
  File "/Users/whit537/lib/python2.7/site.py", line 535, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/whit537/lib/python2.7/site.py", line 268, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/whit537/lib/python2.7/site.py", line 243, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/whit537/lib/python2.7/site.py", line 233, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/whit537/lib/python2.7/sysconfig.py", line 535, in get_config_var
    return get_config_vars().get(name)
  File "/Users/whit537/lib/python2.7/sysconfig.py", line 434, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/Users/whit537/lib/python2.7/sysconfig.py", line 287, in _init_posix
    raise IOError(msg)
IOError: invalid Python installation: unable to open /Users/whit537/lib/python2.7/config/Makefile (No such file or directory)
make: *** [clean] Error 1
$
```

**Comment by pjz** [comment]
But since Google Code is dying, the more pertinent link is https://github.com/SimonAlfie/fabricate/issues/43
