### ISSUE TITLE
Tests fail to install pytest properly

### ISSUE THREAD

**Issue by jaraco** [AspenWeb/pando.py#542]
Using the latest master in a clean checkout on OS X under Python 3.5, I invoke `python build.py dev` but it fails to properly install `py.test`. This also makes it impossible to invoke tests with `python build.py analyse`.

```
$ python build.py dev
/Library/Frameworks/Python.framework/Versions/3.5/bin/python3 ./vendor/virtualenv-13.0.3.py --prompt=[aspen] --extra-search-dir=./vendor/bootstrap env
Using base prefix '/Library/Frameworks/Python.framework/Versions/3.5'
New python executable in env/bin/python3
Also creating executable in env/bin/python
Installing setuptools, pip, wheel...done.
env/bin/pip install --no-index --find-links=./vendor/install python-mimeparse>=0.1.4
Ignoring indexes: https://pypi.python.org/simple
Collecting python-mimeparse>=0.1.4
Installing collected packages: python-mimeparse
Successfully installed python-mimeparse-0.1.4
env/bin/pip install --no-index --find-links=./vendor/install first>=2.0.1
Ignoring indexes: https://pypi.python.org/simple
Collecting first>=2.0.1
Installing collected packages: first
Successfully installed first-2.0.1
env/bin/pip install --no-index --find-links=./vendor/install algorithm>=1.0.0
Ignoring indexes: https://pypi.python.org/simple
Collecting algorithm>=1.0.0
Collecting dependency-injection (from algorithm>=1.0.0)
Installing collected packages: dependency-injection, algorithm
Successfully installed algorithm-1.0.0 dependency-injection-1.1.0
env/bin/pip install --no-index --find-links=./vendor/install filesystem_tree>=1.0.1
Ignoring indexes: https://pypi.python.org/simple
Collecting filesystem-tree>=1.0.1
Installing collected packages: filesystem-tree
Successfully installed filesystem-tree-1.0.1
env/bin/pip install --no-index --find-links=./vendor/install dependency_injection>=1.1.0
Ignoring indexes: https://pypi.python.org/simple
Requirement already satisfied (use --upgrade to upgrade): dependency-injection>=1.1.0 in ./env/lib/python3.5/site-packages
env/bin/python setup.py develop
/Users/jaraco/Dropbox/code/public/aspen/env/lib/python3.5/site-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.42-dev' to '0.42.dev0'
  normalized_version,
running develop
running egg_info
creating aspen.egg-info
writing dependency_links to aspen.egg-info/dependency_links.txt
writing aspen.egg-info/PKG-INFO
writing entry points to aspen.egg-info/entry_points.txt
writing top-level names to aspen.egg-info/top_level.txt
writing requirements to aspen.egg-info/requires.txt
writing manifest file 'aspen.egg-info/SOURCES.txt'
reading manifest file 'aspen.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'aspen.egg-info/SOURCES.txt'
running build_ext
Creating /Users/jaraco/Dropbox/code/public/aspen/env/lib/python3.5/site-packages/aspen.egg-link (link to .)
Adding aspen 0.42.dev0 to easy-install.pth file
Installing fcgi_aspen script to /Users/jaraco/Dropbox/code/public/aspen/env/bin

Installed /Users/jaraco/Dropbox/code/public/aspen
Processing dependencies for aspen==0.42.dev0
Searching for filesystem-tree==1.0.1
Best match: filesystem-tree 1.0.1
Adding filesystem-tree 1.0.1 to easy-install.pth file

Using /Users/jaraco/Dropbox/code/public/aspen/env/lib/python3.5/site-packages
Searching for algorithm==1.0.0
Best match: algorithm 1.0.0
Adding algorithm 1.0.0 to easy-install.pth file

Using /Users/jaraco/Dropbox/code/public/aspen/env/lib/python3.5/site-packages
Searching for first==2.0.1
Best match: first 2.0.1
Adding first 2.0.1 to easy-install.pth file

Using /Users/jaraco/Dropbox/code/public/aspen/env/lib/python3.5/site-packages
Searching for python-mimeparse==0.1.4
Best match: python-mimeparse 0.1.4
Adding python-mimeparse 0.1.4 to easy-install.pth file

Using /Users/jaraco/Dropbox/code/public/aspen/env/lib/python3.5/site-packages
Searching for dependency-injection==1.1.0
Best match: dependency-injection 1.1.0
Adding dependency-injection 1.1.0 to easy-install.pth file

Using /Users/jaraco/Dropbox/code/public/aspen/env/lib/python3.5/site-packages
Finished processing dependencies for aspen==0.42.dev0
env/bin/pip install --no-index --find-links=./vendor/test coverage>=3.7.1
Ignoring indexes: https://pypi.python.org/simple
Collecting coverage>=3.7.1
Installing collected packages: coverage
Successfully installed coverage-3.7.1
env/bin/pip install --no-index --find-links=./vendor/test cov-core>=1.7
Ignoring indexes: https://pypi.python.org/simple
Collecting cov-core>=1.7
Requirement already satisfied (use --upgrade to upgrade): coverage>=3.4 in ./env/lib/python3.5/site-packages (from cov-core>=1.7)
Installing collected packages: cov-core
Successfully installed cov-core-1.7
env/bin/pip install --no-index --find-links=./vendor/test py>=1.4.20
Ignoring indexes: https://pypi.python.org/simple
Collecting py>=1.4.20
Installing collected packages: py
Successfully installed py-1.4.20
env/bin/pip install --no-index --find-links=./vendor/test pytest>=2.5.2
Ignoring indexes: https://pypi.python.org/simple
Collecting pytest>=2.5.2
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.20 in ./env/lib/python3.5/site-packages (from pytest>=2.5.2)
Installing collected packages: pytest
Successfully installed pytest-2.5.2
env/bin/pip install --no-index --find-links=./vendor/test pytest-cov>=1.6
Ignoring indexes: https://pypi.python.org/simple
Collecting pytest-cov>=1.6
Requirement already satisfied (use --upgrade to upgrade): pytest>=2.2.3 in ./env/lib/python3.5/site-packages (from pytest-cov>=1.6)
Requirement already satisfied (use --upgrade to upgrade): cov-core>=1.6 in ./env/lib/python3.5/site-packages (from pytest-cov>=1.6)
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.20 in ./env/lib/python3.5/site-packages (from pytest>=2.2.3->pytest-cov>=1.6)
Requirement already satisfied (use --upgrade to upgrade): coverage>=3.4 in ./env/lib/python3.5/site-packages (from cov-core>=1.6->pytest-cov>=1.6)
Installing collected packages: pytest-cov
Successfully installed pytest-cov-1.6
$ env/bin/py.test
Traceback (most recent call last):
  File "env/bin/py.test", line 7, in <module>
    from pytest import main
ImportError: No module named 'pytest'
```

Pytest is installed in the environment, but the installed script is referencing the wrong env:

```
$ head env/bin/py.test
#!/Library/Frameworks/Python.framework/Versions/3.5/bin/python3
```

Surely, since pytest wasn't installed to the system environment, it shouldn't be referencing the system environment.

Running `env/bin/pip uninstall pytest; env/bin/pip install pytest` corrects the issue.

**Comment by pjz** [comment]
...we don't have python3 support yet.

**Comment by pjz** [comment]
Thought the env issue you point out is different, and troubling.  I suspect we need to upgrade either our vendored `virtualenv` or our vendored `pytest` module.... or not vendor them, possibly over @whit537 's objections.

**Comment by jaraco** [comment]
I understand there's not Python 3 support yet. But I am trying to run the tests under Python 3 to understand how deep the compatibility issues go.

I've also found that reinstalling the vendored version of pytest using the env created by the vendored version of virtualenv also works around the issue. There seems to be something happening environmentally by the fact that `build.dev` is being called from another Python process.

**Comment by pjz** [comment]
The workaround in your original post actually installs the latest version of pytest, not the vendored version.  What does `./env/bin/pip freeze |grep pytest` show you?  Also, you say it corrected the issue, but... how?  Is the `#!` line of `./env/bin/py.test` different now?  or does it still reference `#!/Library/Frameworks/Python.framework/Versions/3.5/bin/python3` ?

**Comment by jaraco** [comment]
Indeed, bypassing the vendoring with:

```
$ hg diff --git
diff --git a/build.py b/build.py
--- a/build.py
+++ b/build.py
@@ -85,8 +85,7 @@
     if b"found" in v:
         return envdir
     for dep in ASPEN_DEPS:
-        run(_virt('pip', envdir), 'install', '--no-index',
-            '--find-links=' + INSTALL_DIR, dep)
+        run(_virt('pip', envdir), 'install', dep)
     run(_virt('python', envdir), 'setup.py', 'develop')
     return envdir
 
@@ -97,10 +96,10 @@
     if _virt_version(envdir) < (2, 7):
         TEST_DEPS.insert(0, 'argparse')
     for dep in TEST_DEPS:
-        run(_virt('pip', envdir), 'install', '--no-index',
-            '--find-links=' + TEST_DIR, dep)
+        run(_virt('pip', envdir), 'install', dep)
     return envdir
 
+
 def dev():
     """set up an environment able to run tests in env/"""
     _dev_deps()
```

Then running `build clean dev`, still shows the issue.

**Comment by jaraco** [comment]
> What does ./env/bin/pip freeze |grep pytest show you?

Depends on whether I'm using the vendored version or not, but it shows 2.5.3 or 2.8.5.

> Also, you say it corrected the issue, but... how? Is the #! line of ./env/bin/py.test different now?

Yes, if pytest is uninstalled and reinstalled by not using build.py, the header of env/bin/py.test shows the virtualenv python instead.

In my experience, the distinguishing factor is how pip is invoked - through build.py or natively through env/bin/pip.

**Comment by jaraco** [comment]
Interestingly, I don't have the issue under Python 2.7. So it seems Python 3 is also a factor; perhaps there's a virtualenv bug in Python 3.5 or perhaps the issue is in fabricate.

**Comment by pjz** [comment]
build.py just calls `env/bin/pip`... your transcript even says:
```
env/bin/pip install --no-index --find-links=./vendor/test pytest>=2.5.2
Ignoring indexes: https://pypi.python.org/simple
Collecting pytest>=2.5.2
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.20 in ./env/lib/python3.5/site-packages (from pytest>=2.5.2)
Installing collected packages: pytest
Successfully installed pytest-2.5.2
```

So I really don't know what's going on.

**Comment by jaraco** [comment]
Right. Weird, huh?

Here's another workaround: creating a pyvenv in advance.

```
$ python build.py clean
...
$ python -m venv env
$ python build.py dev
...
$ head -n 1 env/bin/py.test
#!/Users/jaraco/Dropbox/code/public/aspen/env/bin/python3
```

**Comment by jaraco** [comment]
However, creating the environment manually using virtualenv 13.1.2, then running `python build.py dev` still has the wrong header. Same with virtualenv 14.0.0.

I would say that what I've encountered is a bug in pip or virtualenv on Python 3.x, except that it only happens when I run through build.py.

**Comment by jaraco** [comment]
I was able to recreate the issue without build.py:

```
$ cat > invoke.py
import sys
import subprocess

subprocess.Popen(sys.argv[1:]).wait()
$ rm -Rf env
$ python -m virtualenv --version
14.0.0
$ python --version
Python 3.5.1
$ python -m virtualenv env
Using base prefix '/Library/Frameworks/Python.framework/Versions/3.5'
New python executable in /Users/jaraco/Dropbox/code/public/aspen/env/bin/python3
Also creating executable in /Users/jaraco/Dropbox/code/public/aspen/env/bin/python
Installing setuptools, pip, wheel...done.
$ python invoke.py env/bin/pip install pytest
Collecting pytest
  Using cached pytest-2.8.5-py2.py3-none-any.whl
Collecting py>=1.4.29 (from pytest)
  Using cached py-1.4.31-py2.py3-none-any.whl
Installing collected packages: py, pytest
Successfully installed py-1.4.31 pytest-2.8.5
$ head -n 1 env/bin/py.test
#!/Library/Frameworks/Python.framework/Versions/3.5/bin/python3
```

**Comment by jaraco** [comment]
Changing invoke.py to the following also corrects the behavior:

```
import sys
import os
import subprocess

env = dict(os.environ)
env.pop('__PYVENV_LAUNCHER__')

subprocess.Popen(sys.argv[1:], env=env).wait()
```

I think that may be a bug in virtualenv. I'll check with that project.

**Comment by whit537** [comment]
> on OS X

!!! Say it ain't so, @jaraco! :open_mouth:

**Comment by jaraco** [comment]
It is true. Switched in May. Cold turkey. No boot camp. Overall I'm happy with the switch.

**Comment by whit537** [comment]
Well I'll never. Welcome to the dark side. :dromedary_camel: :)

**Comment by whit537** [comment]
@jaraco The codebase has a seen a lot of activity recently, ahead of a new major version targetted for a couple weeks. Mind trying to reproduce this issue with the head of master?

**Comment by whit537** [comment]
> a seen a lot of activity recently

... including Python 3 support! #524 💃

**Comment by jaraco** [comment]
Excellent. I'll plan to look soon.

**Comment by jaraco** [comment]
Sadly, the problem persists.

```
$ git clone gh://AspenWeb/pando.py
Cloning into 'pando.py'...
remote: Counting objects: 19823, done.
remote: Compressing objects: 100% (215/215), done.
remote: Total 19823 (delta 128), reused 0 (delta 0), pack-reused 19606
Receiving objects: 100% (19823/19823), 16.66 MiB | 11.30 MiB/s, done.
Resolving deltas: 100% (10799/10799), done.
$ cd pando.py 
$ python -V
Python 3.6.0b1
$ python build.py dev
/Library/Frameworks/Python.framework/Versions/3.6/bin/python3 -m virtualenv --prompt=[pando] env
Using base prefix '/Library/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/jaraco/Dropbox/code/public/pando.py/env/bin/python3
Also creating executable in /Users/jaraco/Dropbox/code/public/pando.py/env/bin/python
Installing setuptools, pip, wheel...done.
pip install tox
Collecting tox
  Using cached tox-2.3.1-py2.py3-none-any.whl
Collecting pluggy<0.4.0,>=0.3.0 (from tox)
  Using cached pluggy-0.3.1-py2.py3-none-any.whl
Collecting virtualenv>=1.11.2 (from tox)
  Using cached virtualenv-15.0.3-py2.py3-none-any.whl
Collecting py>=1.4.17 (from tox)
  Using cached py-1.4.31-py2.py3-none-any.whl
Installing collected packages: pluggy, virtualenv, py, tox
Successfully installed pluggy-0.3.1 py-1.4.31 tox-2.3.1 virtualenv-15.0.3
tox --notest --skip-missing-interpreters
Traceback (most recent call last):
  File "env/bin/tox", line 7, in <module>
    from tox import cmdline
ModuleNotFoundError: No module named 'tox'
fabricate: 'tox' exited with status 1
```

**Comment by jaraco** [comment]
Although I should say, the issue doesn't lie with pando - it lies with virtualenv and Python. However, you can work around the issue by implementing [this patch](https://github.com/jaraco/aspen/commit/486dee7fcba0b6392e1acbcbafe697b4ce7a056c). Is that something you would like to consider for this project? If not, I'll just drop it.
